basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: team@addishiwot.org
    name: Addis Hiwot Dev Team
  description: Backend API for the Addis Hiwot platform.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Addis Hiwot API
  version: "1.0"
paths: {}
swagger: "2.0"
