name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.10"

      - name: Build
        working-directory: ./Backend
        run: go build -v ./...

      - name: Test
        working-directory: ./Backend
        run: go test -v ./...

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Docker image
        working-directory: ./Backend
        run: docker build -t addis-hiwot:latest .
